---
- name: Converge
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.update
    - role: robertdebock.buildtools
    - role: robertdebock.python-pip
    - role: robertdebock.httpd
    - role: ansible-role-php
